// <auto-generated />
using System;
using Learning_hub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Learning_hub.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Learning_hub.Data.DataCourse", b =>
                {
                    b.Property<string>("IdKhoaHoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DanhMuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanhMucCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdNguoiDay")
                        .HasColumnType("int");

                    b.Property<string>("KienThucThuDuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongHocVien")
                        .HasColumnType("int");

                    b.Property<string>("TieuDeKhoaHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhoaHoc");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Learning_hub.Data.DataDocument", b =>
                {
                    b.Property<int>("IdTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DuongDan")
                        .HasColumnType("int");

                    b.Property<int>("IdBaiGiang")
                        .HasColumnType("int");

                    b.Property<string>("LoaiTaiLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiLieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTaiLieu");

                    b.ToTable("DataDocuments");
                });

            modelBuilder.Entity("Learning_hub.Data.DataEducationProgram", b =>
                {
                    b.Property<int>("IdChuongTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdNguoiDay")
                        .HasColumnType("int");

                    b.Property<string>("TieuDeMuc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChuongTrinh");

                    b.ToTable("DataEducationPrograms");
                });

            modelBuilder.Entity("Learning_hub.Data.DataLesson", b =>
                {
                    b.Property<int>("IdBaiGiang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("TieuDeBaiGiang")
                        .HasColumnType("int");

                    b.HasKey("IdBaiGiang");

                    b.ToTable("DataLessons");
                });

            modelBuilder.Entity("Learning_hub.Data.DataRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModelIdUser")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserModelIdUser");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Learning_hub.Data.DataRequestApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeachingFields")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestApproval");
                });

            modelBuilder.Entity("Learning_hub.Data.DataTeacher", b =>
                {
                    b.Property<string>("IdNguoiDay")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiThieuBanThan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinhVucDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhTrang")
                        .HasColumnType("int");

                    b.HasKey("IdNguoiDay");

                    b.ToTable("DataTeachers");
                });

            modelBuilder.Entity("Learning_hub.Data.DataUser", b =>
                {
                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CCCD")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Role")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Learning_hub.Data.DataRefreshToken", b =>
                {
                    b.HasOne("Learning_hub.Data.DataUser", "UserModel")
                        .WithMany()
                        .HasForeignKey("UserModelIdUser");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("Learning_hub.Data.DataTeacher", b =>
                {
                    b.HasOne("Learning_hub.Data.DataUser", "UserModel")
                        .WithMany()
                        .HasForeignKey("IdNguoiDay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });
#pragma warning restore 612, 618
        }
    }
}
